/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RentalTermsRouteImport } from './routes/rental-terms'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradingIndexRouteImport } from './routes/trading.index'
import { Route as FabricationIndexRouteImport } from './routes/fabrication.index'
import { Route as EquipmentRentalIndexRouteImport } from './routes/equipment-rental.index'
import { Route as TradingSlugRouteImport } from './routes/trading.$slug'
import { Route as FabricationSlugRouteImport } from './routes/fabrication.$slug'
import { Route as EquipmentRentalSlugRouteImport } from './routes/equipment-rental.$slug'

const RentalTermsRoute = RentalTermsRouteImport.update({
  id: '/rental-terms',
  path: '/rental-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationIndexRoute = FabricationIndexRouteImport.update({
  id: '/fabrication/',
  path: '/fabrication/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRentalIndexRoute = EquipmentRentalIndexRouteImport.update({
  id: '/equipment-rental/',
  path: '/equipment-rental/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingSlugRoute = TradingSlugRouteImport.update({
  id: '/trading/$slug',
  path: '/trading/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationSlugRoute = FabricationSlugRouteImport.update({
  id: '/fabrication/$slug',
  path: '/fabrication/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRentalSlugRoute = EquipmentRentalSlugRouteImport.update({
  id: '/equipment-rental/$slug',
  path: '/equipment-rental/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rental': typeof RentalRoute
  '/rental-terms': typeof RentalTermsRoute
  '/equipment-rental/$slug': typeof EquipmentRentalSlugRoute
  '/fabrication/$slug': typeof FabricationSlugRoute
  '/trading/$slug': typeof TradingSlugRoute
  '/equipment-rental/': typeof EquipmentRentalIndexRoute
  '/fabrication/': typeof FabricationIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rental': typeof RentalRoute
  '/rental-terms': typeof RentalTermsRoute
  '/equipment-rental/$slug': typeof EquipmentRentalSlugRoute
  '/fabrication/$slug': typeof FabricationSlugRoute
  '/trading/$slug': typeof TradingSlugRoute
  '/equipment-rental': typeof EquipmentRentalIndexRoute
  '/fabrication': typeof FabricationIndexRoute
  '/trading': typeof TradingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rental': typeof RentalRoute
  '/rental-terms': typeof RentalTermsRoute
  '/equipment-rental/$slug': typeof EquipmentRentalSlugRoute
  '/fabrication/$slug': typeof FabricationSlugRoute
  '/trading/$slug': typeof TradingSlugRoute
  '/equipment-rental/': typeof EquipmentRentalIndexRoute
  '/fabrication/': typeof FabricationIndexRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/rental'
    | '/rental-terms'
    | '/equipment-rental/$slug'
    | '/fabrication/$slug'
    | '/trading/$slug'
    | '/equipment-rental/'
    | '/fabrication/'
    | '/trading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/rental'
    | '/rental-terms'
    | '/equipment-rental/$slug'
    | '/fabrication/$slug'
    | '/trading/$slug'
    | '/equipment-rental'
    | '/fabrication'
    | '/trading'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/rental'
    | '/rental-terms'
    | '/equipment-rental/$slug'
    | '/fabrication/$slug'
    | '/trading/$slug'
    | '/equipment-rental/'
    | '/fabrication/'
    | '/trading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RentalRoute: typeof RentalRoute
  RentalTermsRoute: typeof RentalTermsRoute
  EquipmentRentalSlugRoute: typeof EquipmentRentalSlugRoute
  FabricationSlugRoute: typeof FabricationSlugRoute
  TradingSlugRoute: typeof TradingSlugRoute
  EquipmentRentalIndexRoute: typeof EquipmentRentalIndexRoute
  FabricationIndexRoute: typeof FabricationIndexRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rental-terms': {
      id: '/rental-terms'
      path: '/rental-terms'
      fullPath: '/rental-terms'
      preLoaderRoute: typeof RentalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication/': {
      id: '/fabrication/'
      path: '/fabrication'
      fullPath: '/fabrication/'
      preLoaderRoute: typeof FabricationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-rental/': {
      id: '/equipment-rental/'
      path: '/equipment-rental'
      fullPath: '/equipment-rental/'
      preLoaderRoute: typeof EquipmentRentalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/$slug': {
      id: '/trading/$slug'
      path: '/trading/$slug'
      fullPath: '/trading/$slug'
      preLoaderRoute: typeof TradingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication/$slug': {
      id: '/fabrication/$slug'
      path: '/fabrication/$slug'
      fullPath: '/fabrication/$slug'
      preLoaderRoute: typeof FabricationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-rental/$slug': {
      id: '/equipment-rental/$slug'
      path: '/equipment-rental/$slug'
      fullPath: '/equipment-rental/$slug'
      preLoaderRoute: typeof EquipmentRentalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RentalRoute: RentalRoute,
  RentalTermsRoute: RentalTermsRoute,
  EquipmentRentalSlugRoute: EquipmentRentalSlugRoute,
  FabricationSlugRoute: FabricationSlugRoute,
  TradingSlugRoute: TradingSlugRoute,
  EquipmentRentalIndexRoute: EquipmentRentalIndexRoute,
  FabricationIndexRoute: FabricationIndexRoute,
  TradingIndexRoute: TradingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
